package com.lunna.insight.Models.DB;


import com.lunna.insight.Models.DB.Profile.MmUsers;
import org.hibernate.annotations.*;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.HashSet;
import java.util.Set;

// Generated Jan 17, 2017 3:02:17 PM by Hibernate Tools 4.3.1

/**
 * MmEntity generated by hbm2java
 */
@Entity
@DynamicInsert
@DynamicUpdate
@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "MM_Entity"
    , uniqueConstraints = @UniqueConstraint(columnNames = "Domain_Name")
)
public class MmEntity implements java.io.Serializable {


    private int entId;
//    private MmCurrencies mmCurrencies;
    private boolean status;
    private String domainName;
    private String entLicense;

    private Set<MmUsers> mmUserses = new HashSet<MmUsers>(0);


    public MmEntity() {
    }

    public MmEntity(int entId) {
        this.entId = entId;
    }

//    public MmEntity(int entId, MmCurrencies mmCurrencies, boolean status, String domainName) {
//        this.entId = entId;
//        this.mmCurrencies = mmCurrencies;
//        this.status = status;
//        this.domainName = domainName;
//    }

    public MmEntity(int entId,   boolean status, String domainName ) {
        this.entId = entId;
        this.status = status;
        this.domainName = domainName;
        this.mmUserses = mmUserses;

    }

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator")
    @Type(type = "pg-uuid")

    @Column(name = "Ent_ID", unique = true, nullable = false)
    public int getEntId() {
        return this.entId;
    }

    public void setEntId(int entId) {
        this.entId = entId;
    }

//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "Currency_ID")
//    public MmCurrencies getMmCurrencies() {
//        return this.mmCurrencies;
//    }
//
//    public void setMmCurrencies(MmCurrencies mmCurrencies) {
//        this.mmCurrencies = mmCurrencies;
//    }


    @Column(name = "Status", nullable = false)
    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }


    @Column(name = "Ent_License", length = 500)
    public String getEntLicense() {
        return this.entLicense;
    }

    public void setEntLicense(String entLicense) {
        this.entLicense = entLicense;
    }

    @Column(name = "Domain_Name", unique = true, nullable = false, length = 50)
    public String getDomainName() {
        return this.domainName;
    }

    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }


}


